import React from "react";
import './CVPreview.css';

function CVPreview() {
    return (
        <div className='cvpreview'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis justo consectetur lectus interdum pulvinar. In justo sem, feugiat non tellus vel, iaculis ornare nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi lacinia semper malesuada. Integer vitae condimentum augue, sit amet accumsan dui. Duis scelerisque felis ut eros aliquet iaculis. Aliquam euismod suscipit urna, eget condimentum diam ultrices quis. In et turpis eget urna posuere vehicula et sed orci. Ut vitae feugiat neque, ac vulputate neque. Cras varius accumsan neque vel varius. Aenean consequat vestibulum nibh at rhoncus. Phasellus id aliquet leo. Cras volutpat finibus iaculis. Nullam scelerisque lorem eget urna viverra, id dictum tellus dictum. Vestibulum sollicitudin viverra lorem id consequat.

Nunc tristique mattis felis non placerat. Pellentesque non purus elit. In est lectus, congue luctus ligula a, pellentesque auctor arcu. Donec id neque magna. Aenean vel bibendum ipsum, in tristique tortor. Vivamus maximus vulputate neque, ut maximus est vehicula sit amet. Vestibulum luctus dui et quam tempus, a porta purus placerat. Vivamus tincidunt elit vel mauris finibus, non consequat risus pellentesque. Suspendisse nisi nunc, sagittis a enim et, ultricies volutpat orci. Duis ultrices pellentesque fringilla. Cras ut turpis fringilla, pellentesque erat eget, dignissim nunc. Pellentesque diam ligula, malesuada nec diam a, imperdiet viverra sem. Nulla commodo mattis felis, a efficitur risus ultricies ac. Ut vitae nunc vel sem tincidunt cursus.

Nulla porta purus ullamcorper urna sodales tristique. Nulla vehicula nunc massa, at euismod tellus sollicitudin sit amet. Mauris venenatis sem metus, at ornare ante suscipit et. Maecenas et mi orci. Fusce congue arcu dolor. Donec venenatis nibh odio, vitae tincidunt mi cursus eu. Fusce in tempus neque, efficitur suscipit dolor. Duis lobortis, leo et interdum lobortis, ante nunc euismod enim, efficitur tristique velit elit quis nisl. Quisque tempus magna erat, eget elementum nisl tempus sed. Pellentesque euismod magna vitae sem consectetur, et lobortis nunc porta. Aenean faucibus elit et tincidunt fermentum. In a leo volutpat, consectetur nisl sed, rhoncus ligula. Aliquam eleifend semper est, id posuere lorem cursus sit amet.

Mauris vitae sem urna. Nullam malesuada nisi ut mauris lobortis commodo. Morbi eget augue facilisis, ullamcorper tellus id, sodales dui. Proin id odio ut sem scelerisque pellentesque. Praesent ac imperdiet est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum a eros dapibus, ullamcorper purus vitae, maximus ex. Proin porttitor ultrices finibus. Integer scelerisque, lacus et tempus consequat, eros augue auctor tellus, nec faucibus est purus sit amet quam. Aliquam pellentesque dapibus lorem, id viverra ligula vulputate at. Morbi tincidunt ut velit a efficitur. Vestibulum at neque at libero mollis volutpat nec ac augue.

Aliquam venenatis dolor nisl, eget pellentesque lorem rutrum sit amet. Vestibulum at erat velit. Aenean nibh neque, iaculis ac mauris eu, pellentesque fringilla diam. Fusce volutpat enim et felis accumsan rhoncus. Nullam maximus at elit vitae dapibus. Nullam varius dictum tempus. Nunc aliquam ipsum sit amet enim congue, vel tempus augue molestie. Ut vitae posuere purus. Aliquam laoreet ut ante sed laoreet. Quisque lacinia dolor felis, nec feugiat dui finibus non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer ullamcorper velit sed dolor dapibus, facilisis accumsan enim egestas. Vestibulum ultricies erat nec auctor vehicula. Nulla facilisi. In vitae felis purus.

In elementum semper rhoncus. Mauris vel consequat mi, at tincidunt arcu. Mauris ultrices ac orci mattis malesuada. Curabitur sed laoreet nisl. Donec scelerisque est et nisi convallis ornare. Duis vulputate viverra ullamcorper. Mauris lacinia cursus molestie. Sed aliquam, risus quis euismod congue, libero sem scelerisque ante, non porta leo nibh at nunc. Proin dignissim et lectus at faucibus.

Aliquam vel porttitor urna. Morbi vel maximus enim. Vestibulum suscipit in dui id molestie. Phasellus quis tempor nibh, eu ullamcorper augue. Nulla facilisi. Integer volutpat magna felis, ac volutpat tortor venenatis sit amet. Vestibulum elit sapien, suscipit sit amet laoreet efficitur, pulvinar ac tellus. Nunc sed dolor ac diam rhoncus egestas vitae vel erat. Suspendisse bibendum vehicula congue. Nullam vitae efficitur nisl, in blandit nibh.

Cras turpis diam, consectetur posuere elit ac, maximus accumsan sem. Phasellus enim sapien, auctor gravida felis sit amet, facilisis elementum eros. Aenean quis gravida turpis. Integer sollicitudin mollis tempus. Fusce non orci aliquam, tempor ante id, sagittis nibh. Morbi porttitor, lectus quis sodales tempus, dui dolor hendrerit arcu, nec varius metus odio ac est. Pellentesque posuere erat suscipit magna gravida, sed lacinia dui rutrum. Vivamus id aliquet purus. Etiam nec felis vitae nisl volutpat volutpat nec sollicitudin mi.

Mauris gravida, leo ut rutrum venenatis, lacus lectus viverra neque, vel mattis odio est a neque. Vestibulum interdum eros ex, sed aliquet purus viverra vel. Morbi eget ex vel est finibus pretium. Phasellus at consequat lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec venenatis orci est, a imperdiet nibh congue vel. Duis ut lacus at risus faucibus condimentum. In hac habitasse platea dictumst. Morbi eleifend nisl erat, sit amet placerat urna dictum ut. Cras sagittis sagittis placerat. Integer ultricies ligula ac justo luctus, quis tristique ex ullamcorper. Fusce condimentum auctor orci, et consectetur leo aliquam eu. Duis vel nulla ac libero faucibus pellentesque. Curabitur molestie quam vel metus dignissim, id aliquet urna commodo. In ac interdum ipsum, quis sollicitudin turpis. Suspendisse vitae ante varius, rutrum augue nec, ullamcorper nibh.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu tempor odio. Nulla semper fermentum aliquet. Nullam ornare dui vel nunc mattis, ac feugiat metus porta. Donec mollis purus at convallis sollicitudin. Sed aliquet massa a mauris vestibulum tincidunt. Nunc suscipit rhoncus sollicitudin. Proin consectetur lectus vitae lectus ornare, nec rutrum nibh aliquam. Sed lorem purus, tristique vel arcu vitae, finibus congue felis. Pellentesque maximus tortor non tincidunt ultrices. Aliquam vehicula fermentum posuere. Mauris bibendum lorem id arcu pharetra, ut feugiat ipsum dignissim. Mauris fringilla erat a libero convallis congue. Proin eget ipsum turpis. Sed aliquam nunc nec urna feugiat tincidunt.
        </div>
    );
}

export default CVPreview;